










    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },


    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },

requires-python = ">=3.10"













git_describe_command = "git describe --dirty --tags --long --match ordeq-viz/*"









# Ignore unresolved imports and docstring missing in tests


[tool.pytest.ini_options]
pythonpath = ["src", "tests"]

[tool.coverage.run]
omit = [
    "src/ordeq_viz/_version.py"
]
