[build-system]
requires = ["setuptools>=75.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ordeq_test_utils"
description = "Testing utilities for Ordeq packages - not distributed on PyPI"
version = "0.1.0"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },
]
maintainers = [
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },
]
requires-python = ">=3.10"
dependencies = [
    "mypy>=0.18.2",  # for snapshot testing
]

[tool.ordeq-dev]
logo_url = ""
group = "developer-tools"

[dependency-groups]
test = []

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

