










    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },


    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },

requires-python = ">=3.10"

    "ordeq>=0.2.1",















git_describe_command = "git describe --dirty --tags --long --match ordeq-files/*"





[tool.pytest.ini_options]
pythonpath = ["src", "tests"]
addopts = "--doctest-modules"

[tool.coverage.run]
omit = [
    "src/ordeq_files/_version.py"
]
