










    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },


    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },

requires-python = ">=3.10"
dependencies = ["ordeq>=0.2.1"]












git_describe_command = "git describe --dirty --tags --long --match ordeq-args/*"





[tool.pytest.ini_options]
pythonpath = ["src", "tests"]
addopts = "--doctest-modules"

[tool.coverage.run]
omit = [
    "src/ordeq_args/_version.py"
]
