[build-system]
requires = ["setuptools>=75.0", "setuptools_scm>=8.1.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ordeq_boto3"
dynamic = ["version"]
readme = "../../README.md"
license = "MIT"
license-files = ["../../LICENSE"]
authors = [
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },
]
maintainers = [
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },
]
requires-python = ">=3.10"
dependencies = [
    "ordeq>=1.0.0",
    "boto3",
]

[dependency-groups]
test = [
    { include-group = "types" },
    "minio==7.2.15",
    "testcontainers==4.8.1",
]
types = [
    "boto3-stubs[s3]",
]

[tool.setuptools_scm]
root = "../../"
version_file = "src/ordeq_boto3/_version.py"
tag_regex = "^ordeq-boto3/(?:[\\w-]+-)?(?P<version>[vV]?\\d+(?:\\.\\d+){0,2}[^\\+]*)(?:\\+.*)?$"
git_describe_command = "git describe --dirty --tags --long --match ordeq-boto3/*"

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src", "tests"]
addopts = "--doctest-modules"

[tool.coverage.run]
omit = [
    "src/ordeq_boto3/_version.py"
]
