[build-system]
requires = ["setuptools>=75.0", "setuptools_scm>=8.1.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ordeq_boto3"
description = "Boto3 integration for Ordeq"
dynamic = ["version"]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },
    { name = "Soheil Moattar"},
]
maintainers = [
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },
    { name = "Soheil Moattar"},
]
requires-python = ">=3.10"
dependencies = [
    "ordeq>=1.0.0",
    "boto3",
]

[tool.ordeq-dev]
group = "ios"
logo_url = "https://boto3typed.gallerycdn.vsassets.io/extensions/boto3typed/boto3-ide/0.5.4/1680224848596/Microsoft.VisualStudio.Services.Icons.Default"

[dependency-groups]
test = [
    { include-group = "types" },
    "minio==7.2.15",
    "pytest",
    "testcontainers==4.8.1",
]
types = [
    "boto3-stubs[s3]",
    "mypy-boto3-s3",
]

[tool.setuptools_scm]
root = "../../"
version_file = "src/ordeq_boto3/_version.py"
tag_regex = "^ordeq-boto3/(?:[\\w-]+-)?(?P<version>[vV]?\\d+(?:\\.\\d+){0,2}[^\\+]*)(?:\\+.*)?$"
git_describe_command = "git describe --dirty --tags --long --match ordeq-boto3/*"

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[tool.coverage.run]
omit = [
    "src/ordeq_boto3/_version.py"
]
