










    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },


    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },

requires-python = ">=3.10"

    "ordeq>=0.2.1",
    "pandas",




test = [
    "openpyxl",
    "pyarrow"
]





git_describe_command = "git describe --dirty --tags --long --match ordeq-pandas/*"





[tool.pytest.ini_options]
pythonpath = ["src", "tests"]


[tool.coverage.run]
omit = [
    "src/ordeq_pandas/_version.py"
]
