










    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },


    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" }

requires-python = ">=3.10"





    "mypy>=1.17"  # for snapshot testing






git_describe_command = "git describe --dirty --tags --long --match ordeq/*"





[tool.pytest.ini_options]
pythonpath = ["src", "tests"]

[tool.coverage.run]
omit = [
    "src/ordeq/_version.py"
]
