[project]
name = "single-file"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ordeq",
    "ordeq-yaml",
    "ordeq-pandas"
]
