nav:
  - Getting started:
      - Quickstart: index.md
      - getting-started/introduction.md
      - Concepts:
          - IO: getting-started/concepts/io.md
          - Nodes: getting-started/concepts/nodes.md
          - Catalogs: getting-started/concepts/catalogs.md
          - Hooks: getting-started/concepts/hooks.md
  - Guides & examples:
      - Starting a new project: guides/starting_a_new_project.md
      - Running & visualising: guides/run_and_viz.md
      - Nodes:
          - Node parameters: guides/node_parameters.md
          - Testing nodes: guides/testing_nodes.md
      - IO:
          - Custom IO: guides/custom_io.md
          - Parametrizing IO: guides/parametrized_io.md
          - Lazy IO: guides/lazy_io.md
          - Cloud storage: guides/cloud_storage.md
      - Hooks:
          - Benchmark runtimes: guides/examples/benchmark_node_runtime.md
      - Adopting Ordeq:
          - Coming from Kedro: guides/kedro.md
      - Integrations:
          - Docker: guides/integrations/docker.md
  - Reference:
      - Packages: packages.md
      - API: api
  - Contributing:
      - How to: CONTRIBUTING.md
      - Acknowledgements: contributing/acknowledgements.md
      - Documentation setup: contributing/documentation.md
