graph TB
	rag_pipeline.catalog:pdf_documents --> rag_pipeline.rag.indexer:create_vector_index
	rag_pipeline.catalog:llm_vision_retrieval_model --> rag_pipeline.rag.indexer:create_vector_index
	rag_pipeline.rag.indexer:create_vector_index --> rag_pipeline.catalog:index
	rag_pipeline.catalog:policies --> rag_pipeline.rag.policies:generate_questions
	rag_pipeline.rag.policies:generate_questions --> rag_pipeline.catalog:questions
	rag_pipeline.catalog:index --> rag_pipeline.rag.retrieval:retrieve
	rag_pipeline.catalog:questions --> rag_pipeline.rag.retrieval:retrieve
	rag_pipeline.catalog:llm_vision_retrieval_model --> rag_pipeline.rag.retrieval:retrieve
	rag_pipeline.rag.retrieval:retrieve --> rag_pipeline.catalog:retrieved_pages
	rag_pipeline.catalog:retrieved_pages --> rag_pipeline.rag.retrieval:filter_relevant
	rag_pipeline.catalog:llm_model --> rag_pipeline.rag.retrieval:filter_relevant
	rag_pipeline.rag.retrieval:filter_relevant --> rag_pipeline.catalog:relevant_pages
	rag_pipeline.catalog:questions --> rag_pipeline.rag.question_answering:question_answering
	rag_pipeline.catalog:relevant_pages --> rag_pipeline.rag.question_answering:question_answering
	rag_pipeline.catalog:llm_model --> rag_pipeline.rag.question_answering:question_answering
	rag_pipeline.rag.question_answering:question_answering --> rag_pipeline.catalog:llm_answers
	rag_pipeline.catalog:llm_answers --> rag_pipeline.rag.evaluation:evaluate_answers
	rag_pipeline.catalog:llm_model --> rag_pipeline.rag.evaluation:evaluate_answers
	rag_pipeline.rag.evaluation:evaluate_answers --> rag_pipeline.catalog:metrics
	rag_pipeline.catalog:llm_answers --> rag_pipeline.rag.annotation:annotate_documents
	rag_pipeline.catalog:pdf_documents --> rag_pipeline.rag.annotation:annotate_documents
	rag_pipeline.rag.annotation:annotate_documents --> rag_pipeline.catalog:pdfs_documents_annotated

	rag_pipeline.rag.indexer:create_vector_index@{shape: rounded, label: "create_vector_index"}
	rag_pipeline.rag.policies:generate_questions@{shape: rounded, label: "generate_questions"}
	rag_pipeline.rag.retrieval:retrieve@{shape: rounded, label: "retrieve"}
	rag_pipeline.rag.retrieval:filter_relevant@{shape: rounded, label: "filter_relevant"}
	rag_pipeline.catalog:retrieved_pages@{shape: rect, label: "retrieved_pages"}
	rag_pipeline.rag.question_answering:question_answering@{shape: rounded, label: "question_answering"}
	rag_pipeline.rag.evaluation:evaluate_answers@{shape: rounded, label: "evaluate_answers"}
	rag_pipeline.rag.annotation:annotate_documents@{shape: rounded, label: "annotate_documents"}
	rag_pipeline.catalog:index@{shape: rect, label: "index"}
	rag_pipeline.catalog:llm_answers@{shape: rect, label: "llm_answers"}
	rag_pipeline.catalog:llm_model@{shape: rect, label: "llm_model"}
	rag_pipeline.catalog:llm_vision_retrieval_model@{shape: rect, label: "llm_vision_retrieval_model"}
	rag_pipeline.catalog:metrics@{shape: rect, label: "metrics"}
	rag_pipeline.catalog:pdf_documents@{shape: rect, label: "pdf_documents"}
	rag_pipeline.catalog:pdfs_documents_annotated@{shape: rect, label: "pdfs_documents_annotated"}
	rag_pipeline.catalog:policies@{shape: rect, label: "policies"}
	rag_pipeline.catalog:questions@{shape: rect, label: "questions"}
	rag_pipeline.catalog:relevant_pages@{shape: rect, label: "relevant_pages"}

	class rag_pipeline.rag.indexer:create_vector_index,rag_pipeline.rag.policies:generate_questions,rag_pipeline.rag.retrieval:retrieve,rag_pipeline.rag.retrieval:filter_relevant,rag_pipeline.rag.question_answering:question_answering,rag_pipeline.rag.evaluation:evaluate_answers,rag_pipeline.rag.annotation:annotate_documents node
	class rag_pipeline.catalog:retrieved_pages,rag_pipeline.catalog:llm_answers,rag_pipeline.catalog:questions,rag_pipeline.catalog:relevant_pages io1
	class rag_pipeline.catalog:index io0
	class rag_pipeline.catalog:llm_model,rag_pipeline.catalog:llm_vision_retrieval_model io5
	class rag_pipeline.catalog:metrics io3
	class rag_pipeline.catalog:pdf_documents,rag_pipeline.catalog:pdfs_documents_annotated io4
	class rag_pipeline.catalog:policies io2
	classDef node fill:#008AD7,color:#FFF
	classDef io fill:#FFD43B
	classDef io0 fill:#66c2a5
	classDef io1 fill:#fc8d62
	classDef io2 fill:#8da0cb
	classDef io3 fill:#e78ac3
	classDef io4 fill:#a6d854
	classDef io5 fill:#ffd92f
