name: Build

on:
  pull_request:
    branches:
      - main

env:
  pythonVersion: '3.10'

jobs:
  docs:
    name: Build docs
    uses: ./.github/workflows/docs.yml
    with:
      publish_docs: false

  packages:
    name: Determine packages in scope
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.set-packages.outputs.packages }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine packages in scope
        id: set-packages
        run: |
          set -e
          PACKAGES=$(ls packages | tr '\n' ',' | sed 's/,$//')
          echo "Packages: $PACKAGES"
          JSON_ARRAY="["
          IFS=',' read -ra ADDR <<< "$PACKAGES"
          for package in "${ADDR[@]}"; do
            JSON_ARRAY+="\"$package\","
          done
          JSON_ARRAY="${JSON_ARRAY%,}]"
          echo "Packages JSON array: $JSON_ARRAY"
          echo "packages=$JSON_ARRAY" >> $GITHUB_OUTPUT

  static_code_analysis:
    name: Check formatting, linting and typing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.pythonVersion }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.pythonVersion }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --all-packages --all-groups --all-extras

      - name: Check formatting
        run: uv run just format

      - name: Check linting
        run: uv run just lint

      - name: Check typing (ty)
        run: uv run just ty

      - name: Check typing (mypy)
        run: uv run just mypy

  test:
    name: Test
    needs: [ packages, static_code_analysis, docs ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.packages.outputs.packages) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.pythonVersion }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.pythonVersion }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --all-packages --group test

      - name: Run unit tests
        run: uv run --group test pytest -v --cov-report=xml:coverage.xml --cov-report=html --cov-append --cov="packages/${{ matrix.package }}/" --cov-fail-under=0 --cov-branch "packages/${{ matrix.package }}/"

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.package }}
          path: '**/coverage.xml'
