---
name: Pull Request Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_pull_request:
    name: Check pull request
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: fix,change,breaking,internal,docs
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(`ordeq-?.+`|(?!ordeq.*).+): '
          verbal_description: 'Pull request title should start with "`[package]`:" or `docs:`, `ci:` etc.'
          github_token: ${{ github.token }}
