name: "Release"

on:
  push:
    tags:
      - ordeq-*/v*  # e.g., ordeq-spark/v1.2.3
      - ordeq/v*  # e.g. ordeq/v1.2.3
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install Python 3.13
        run: uv python install 3.13

      - name: Build
        run: uv build --all-packages --sdist

      - name: Publish
        run: uv publish
