name: "Release"

on:
  push:
    tags:
      - ordeq-*/v*  # e.g., ordeq-spark/v1.2.3
      - ordeq/v*  # e.g. ordeq/v1.2.3
  workflow_dispatch: # this will be disabled after the first release
    inputs:
      tag_name:
        description: 'Tag to release (e.g., ordeq-spark/v1.2.3)'
        required: false
        type: string

env:
  TAG_NAME: ${{ github.event.inputs.tag_name || github.ref_name }}
  PACKAGE_NAME: ${{ (github.event.inputs.tag_name || github.ref_name).split('/')[0] }}

jobs:
  run:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install Python 3.13
        run: uv python install 3.13

      - name: Build
        run: uv build $PACKAGE_NAME --sdist

      - name: Publish
        run: uv publish --package $PACKAGE_NAME
